select*from alerta
Select*from asentamiento
Select*from asistencia
Select*from auditoria
Select*from bitacora_obra
Select*from cimentacion
Select*from compra_material
Select*from concreto_armado
Select*from detalle_compra
Select*from esfuerzo_estructural
Select*from Estudio_Suelo
Select*from EstudioSuelo
Select*from hidraulica
Select*from incidente
Select*from inventario_cemento
Select*from maquinaria
Select*from material
Select*from proveedor
Select*from Proyecto
Select*from riesgo
Select*from rol
Select*from topografia
Select*from trabajador
Select*from usuario
Select*from usuario_rol
